unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-d
set -g mouse on

# Vim pane switching
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

# Dracula Setup
set -g @dracula-show-powerline true
set -g @dracula-plugins "git time ssh-session"
set -g @dracula-time-format "%a %m/%d %H:%M %Z"
set -g @dracula-show-ssh-only-when-connected true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon "#h | #S | #W"
set -g status-position top

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
